[package]
name = "private/private"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
Sift = "csqrl/sift@0.0.8"
t = "osyrisrblx/t@3.1.1"

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
t = "osyrisrblx/t@3.1.1"
